### ISSUE TITLE
NameError: name 'node_db' is not defined

### ISSUE THREAD

**Issue by DK1MI** [n8acl/aslnotify#5]
Thank you very much for this script. I find it very useful!

There is a small bug in the code that results in the following error:

`NameError: name 'node_db' is not defined`

It is fixed by changing 

`status = status + "Node " + str(their_node) + " " + node_info(node_db)`

to

`status = status + "Node " + str(their_node) + " " + node_info(cfg.node_db)`

There is also a small bug in the documention where the prameters of the script seem to be in the wrong order. The line

`python3 </full/path/to>/aslnotify/conn_bot.py 1 12345 54321`

should be 

`python3 </full/path/to>/aslnotify/conn_bot.py 1 54321 12345`

**Comment by n8acl** [comment]
HI Michael! 

Interesting.. I use the aslnotify script here on my own nodes and not seen an issue. Let me take a look and make sure I didn't make a change that I did not push up to the repo. I suspect that is the case. It was probably late night and I had made some changes and just forgot to push...

Thanks for letting me know. I will update this issue when I know more.

Also sorry it took so long for me to get back to you... It's been a little hectic in life lately.

**Comment by n8acl** [comment]
OK.. 

So yes it was exactly what I thought. I did make the change here on my own system and did not push it to the repo. Good catch on that. The script has been updated in the repo.

Second, were you are saying that the parameters are incorrect in the documentation, they are actually correct. The context there at that point is that this is an example command you can run to test to make sure the script is sending to your notification service of choice properly. the node numbers do not matter in this case because the bot is not making any connections on your ASL system. A little farther down in the read me is a section showing an example of what it would look like when you use ASL connect to an actual system. In other words at that point, it would show actual node numbers and it would be their node to your node. The parameters are automatically passed from ASL via the rpt.conf file in the correct order. So yeah at the point you are talking about, the numbers put in there do not matter, they are just filler for the script to be able to send a test message properly.

**Comment by DK1MI** [comment]
Hi,

excellent! Thanks for the fix!
